print(" this is a demo to show how type casting is done\n")

a = int(input("type a number to type cast in diffrent datatypes : \n"))
b = float(a)
c = bin(a)
d = hex(a)
e = oct(a)

print("here the value of the variables and its datatypes are written\n")
print(a)
print(type(a), "\n")
print(b)
print(type(b), "\n")
print(c)
print(type(c), "\n")
print(d)
print(type(d) , "\n")
print(e)
print(type(e) , "\n")